FROM i386/ubuntu:bionic
LABEL maintainer="chebizarro@gmail.com" Description="Base Container for BioPython"

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    wget \
    unzip \
    git \
    language-pack-en \
    build-essential \
    gcc \
    g++ \
    gcc-5 \
    g++-5 \
    make \
    cmake \
    python3-dev \
    python3.6 \
    python3.6-dev \
    python3-pip \
    python3-pil \
    python-psycopg2 \
    postgresql-client \
    r-base \
    clustalw \
    clustalo \
    fasttree \
    t-coffee \
    ncbi-blast+ \
    emboss \
    embassy-phylip \
    phylip \
    mafft \
    muscle \
    samtools \
    phyml \
    wise \
    raxml \
    paml \
    probcons \
    libxft-dev \
    mysql-client \
    hevea \
    texlive-latex-recommended \
    texlive-latex-extra \ 
    && rm -rf /var/lib/apt/lists/*

#for Phylo_CDAO
RUN pip3 install pip --upgrade
RUN pip3 install --upgrade \
    rdflib \
    cython \
    numpy \
    Pillow==5.4.1 \
    matplotlib \
    reportlab \
    pandas \
    networkx \
    mmtf-python \
    mysql-connector-python \
    psycopg2-binary \
    Pygments

#Manual software

#reportlab fonts
RUN wget http://www.reportlab.com/ftp/fonts/pfbfer.zip
WORKDIR /usr/lib/python3.6/dist-packages/reportlab
RUN  mkdir fonts
WORKDIR /usr/lib/python3.6/dist-packages/reportlab/fonts
RUN unzip /pfbfer.zip \
    && mkdir -p /usr/lib/python3.6/dist-packages/reportlab/fonts
WORKDIR /usr/lib/python3.6/dist-packages/reportlab/fonts
RUN unzip /pfbfer.zip
WORKDIR /
RUN rm pfbfer.zip

#genepop
RUN mkdir genepop
WORKDIR /genepop
RUN wget http://kimura.univ-montp2.fr/~rousset/sources.tar.gz \
    && tar zxf sources.tar.gz \
    && g++ -DNO_MODULES -o Genepop GenepopS.cpp -O3 \
    && cp Genepop /usr/bin
WORKDIR /
RUN rm -rf genepop

#msaprobs
RUN wget "http://sourceforge.net/projects/msaprobs/files/latest/download?source=files" -O MSA.tar.gz \
    && tar zxf MSA.tar.gz
WORKDIR /MSAProbs-0.9.7/MSAProbs
RUN make \
    && cp msaprobs /usr/bin
WORKDIR /

#fastsimcoal
RUN wget http://cmpg.unibe.ch/software/fastsimcoal2/downloads/fsc26_linux64.zip \
    && unzip fsc26_linux64.zip \
    && chmod a+x fsc26_linux64/fsc26 \
    && cp fsc26_linux64/fsc26 /usr/bin/fsc26 \
    && rm -rf fsc_*

#DSSP
RUN wget ftp://ftp.cmbi.ru.nl/pub/software/dssp/dssp-2.0.4-linux-amd64 \
    && mv dssp-2.0.4-linux-amd64 /usr/bin/dssp \
    && chmod a+x /usr/bin/dssp

#XXmotif
#Needs gcc/g++ 5/6
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 5
RUN update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 5
RUN wget https://github.com/soedinglab/xxmotif/archive/master.zip \
    && unzip master.zip \
    && rm master.zip \
    && cd xxmotif-master \
    && mkdir build && cd build \
    && cmake .. && make \
    && cp XXmotif $PREFIX/bin \
    && cd / && rm -r xxmotif-master
        
ENV DIALIGN2_DIR /usr/share/dialign
ENV PYTHON_PATH /biopython

RUN locale-gen --no-purge en_GB.UTF-8
ENV LANG en_GB.UTF-8
ENV LANGUAGE en_GB:en
ENV LC_ALL en_GB.UTF-8

#Biopython
RUN git clone https://github.com/biopython/biopython.git
WORKDIR /biopython
RUN python3.6 setup.py install
RUN python3.6 setup.py test --offline

#set default python version to 3.6
RUN touch ~/.bash_aliases \
	  && echo alias python=\'python3.6\' > ~/.bash_aliases
